### ISSUE TITLE
Sight Call 64Bit issue

### ISSUE THREAD

**Issue by vpanditphonegap** [sightcall/iOS-SDK#2]
I am facing issue when try to run the code on iPhone5s and also when try to create the Archive.
When i am trying to install the app on iphone5 it perfectly work fine. SO may be its because you guys are not providing 64Bit support or there is something else. Find the attached screen shot for more help.
![screen shot 2015-02-26 at 4 58 29 pm](https://cloud.githubusercontent.com/assets/6712725/6391126/bb0acdcc-bdd8-11e4-833d-7d7a02f86d94.png)

**Comment by RomainGabriel** [comment]
Hi there,
This is the iOS-SDK-Helper you are trying to build here. Unfortunately, the Helper uses an old SDK version which is indeed not 64-bit compatible.
Regards.
