### ISSUE TITLE
Unable to run iOS SDK Helper Project

### ISSUE THREAD

**Issue by RajChanchal** [sightcall/iOS-SDK#3]
Initially I was having 32 Errors, then I added libc++.dylb (which was not mentioned anywhere to add), I have got 2 Errors and now I cann't solve them. Here are: 
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Rtcc", referenced from:
      objc-class-ref in CallViewController.o
      objc-class-ref in RtccDelegate.o
     (maybe you meant: _OBJC_CLASS_$_RtccDelegate)
ld: symbol(s) not found for architecture x86_64

**Comment by RomainGabriel** [comment]
Hi there,
The iOS-SDK-Helper is actually outdated. We do not support it anymore because it still uses an old SDK version. We highly recommend to have a look at our tutorials instead: https://docs.sightcall.com/GD/02_iOS_SDK/09_Tutorials/
Note: we do not support the iOS simulator. You could try compiling it on an actual iOS device (architecture armv7 for example).

**Comment by RajChanchal** [comment]
Thanks Romain for your prompt reply and informing me about its being outdated. 
Now I downloaded the first tutorial and ran the authentication tutorial (First one), I am facing these errors:

ld: warning: directory not found for option '-F/Users/charles/Desktop/git_sightcall/Tutos/RtccSDK'
ld: warning: ignoring file /Users/MacBook/Downloads/iOS-Tutorials-master/01-authentication/RtccSDK.framework/RtccSDK, missing required architecture i386 in file /Users/MacBook/Downloads/iOS-Tutorials-master/01-authentication/RtccSDK.framework/RtccSDK (2 slices)
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_Rtcc", referenced from:
      objc-class-ref in Model.o
  "_OBJC_CLASS_$_UserType", referenced from:
      objc-class-ref in Model.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by RomainGabriel** [comment]
Well this is the very same problem. "architecture i386" means you are trying to compile the tutorial for the iOS simulator, which is unsupported.

**Comment by RajChanchal** [comment]
I see, Thanks again Romain. I think this thread will help beginners to get started.
